apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZbXR5YVdKaWN6RTFPa1p2VGpreVRsY3hjRFUwZDNOblZGWXpiMk5SU3pCM1VYbEdjelp5U0RKVVZVWnpWSGxQV0hkdmNteDBUVFYzUkU0NFNURmtSVVZOVmtSUFUyd3plVEU9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson