apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: site-image-build-push
spec:
  params:
    - description: registry-domain/namespace where the output image should be pushed.
      name: image-registry-url
      type: string
    - description: version of the image to be built.
      name: image-version
      type: string
  tasks:
    - name: clone-1
      params:
        - name: url
          value: 'https://github.com/bkribbs15/TechLearnings'
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: code-site
    - name: build-push-1
      params:
        - name: IMAGE
          value: $(params.image-registry-url):$(params.image-version)
        - name: DOCKERFILE
          value: './Dockerfile'
        - name: CONTEXT
          value: '.'
      runAfter:
        - clone-1
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: code-site
    - name: update-version-1
      params:
        - name: IMAGE_VERSION
          value: $(params.image-version)
      runAfter:
        - build-push-1
      taskRef:
        name: update-version-task
      workspaces:
        - name: source
          workspace: code-site
  workspaces:
    - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
      name: code-site
